option(SH3DS_ENABLE_SANITIZERS "Enable AddressSanitizer and UndefinedBehaviorSanitizer" OFF)

if(SH3DS_ENABLE_SANITIZERS)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address,undefined)
        message(STATUS "SH3DS: Sanitizers enabled (ASan + UBSan)")
    elseif(MSVC)
        add_compile_options(/fsanitize=address)
        add_compile_definitions(_DISABLE_VECTOR_ANNOTATION _DISABLE_STRING_ANNOTATION)
        message(STATUS "SH3DS: AddressSanitizer enabled (MSVC)")
    else()
        message(WARNING "SH3DS: Sanitizers not supported for this compiler")
    endif()
endif()
